version: 2.1

commands:
  install-dependencies:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - run: corepack enable
      - run: yarn config set -H enableGlobalCache false
      - run: yarn install --immutable

jobs:
  install:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install-dependencies
      - save_cache:
          key: v1-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - node_modules

  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install-dependencies
      - run: yarn lint:css
      - run: yarn lint:js

  format:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install-dependencies
      - run: yarn format:check

  validate:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install-dependencies
      - run: yarn tsc

  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
<<<<<<< Updated upstream
      - install-dependencies
      - run: yarn build:prd
=======
      - restore_cache:
          key: v1-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - run: yarn build
>>>>>>> Stashed changes

workflows:
  all:
    jobs:
      - install
      - lint:
          requires:
            - install
      - format:
          requires:
            - install
      - validate:
          requires:
            - install
      - build:
          requires:
            - install
