version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:lts
    steps:
      - restore_cache:
          key: cache-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - run:
          name: "Install yarn"
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - yarn set version berry
      - yarn install --immutable
      - save_cache:
          key: cache-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - .yarn/cache

  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - restore_cache:
          key: cache-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - yarn lint:css
      - yarn lint:js

  format:
    docker:
      - image: cimg/node:lts
    steps:
      - restore_cache:
          key: cache-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - yarn format:check

  validate:
    docker:
      - image: cimg/node:lts
    steps:
      - restore_cache:
          key: cache-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - yarn tsc

  build:
    docker:
      - image: cimg/node:lts
    steps:
      - restore_cache:
          key: cache-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - yarn build:prd

workflows:
  all:
    jobs:
      - install
      - lint
      - format
      - validate
      - build
