version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          key: yarn-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .pnp.cjs
            - .pnp.loader.mjs

  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - run: yarn lint:css
      - run: yarn lint:js

  format:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - run: yarn format:check

  validate:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - run: yarn tsc

  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}
      - run: yarn build:prd

workflows:
  all:
    jobs:
      - install
      - lint:
          requires:
            - install
      - format:
          requires:
            - install
      - validate:
          requires:
            - install
      - build:
          requires:
            - install
