import enFlag from './en.png';
import ptFlag from './pt.png';

export default {
    summary: `
        I'm passionate for Web development, mainly in terms of Front-end development. I'm always ready to learn and improve my skills. I like working with open-minded, fun, diversified, and dynamic teams with fresh ideas that push the boundaries.
        I have a good knowledge of JavaScript which allows me to code up from scratch a fully responsive and mobile first site in plain HTML5, CSS3, React and NodeJS (for example).
    `,
    languages: [
        { name: 'Portuguese', code: 'pt', flag: ptFlag, level: 'Native' },
        { name: 'English', code: 'en', flag: enFlag, level: 'Proficient' },
    ],
    skills: [
        { name: 'HTML 5', icon: 'html5' },
        { name: 'CSS3', icon: 'css3' },
        { name: 'SASS', icon: 'sass' },
        { name: 'JavaScript', icon: 'js' },
        { name: 'React', icon: 'react' },
        { name: 'Redux' },
        { name: 'Jasmine' },
        { name: 'Jest' },
        { name: 'Webpack' },
        { name: 'Node.js', icon: 'node-js' },
        { name: 'jQuery' },
        { name: 'Angular', icon: 'angular' },
        { name: 'PHP', icon: 'php' },
        { name: 'Laravel' },
        { name: 'CakePHP' },
        { name: 'MySQL' },
        { name: 'XML' },
        { name: 'JSON' },
        { name: 'Twitter Bootstrap' },
        { name: 'Gulp', icon: 'gulp' },
        { name: 'Java', icon: 'java' },
        { name: 'Photoshop' },
        { name: 'REST' },
        { name: 'Web Development' },
        { name: 'XML Schema' },
        { name: 'XPath' },
        { name: 'XQuery' },
        { name: 'XSLT' },
        { name: 'PostgreSQL' },
        { name: 'Microsoft SQL Server' },
        { name: 'Mac OS X', icon: 'apple' },
        { name: 'Windows', icon: 'windows' },
        { name: 'Linux', icon: 'linux' },
        { name: 'UML' },
        { name: 'LaTeX' },
        { name: 'Design Patterns' },
        { name: 'OOP' },
        { name: 'Software Engineering' },
        { name: 'User Interface Design' },
    ],
    pages: [
        {
            name: 'LinkedIn',
            icon: 'linkedin',
            url: 'https://www.linkedin.com/in/bensampaio',
        },
        {
            name: 'Github',
            icon: 'github-square',
            url: 'https://github.com/bensampaio',
        },
        {
            name: 'Facebook',
            icon: 'facebook-square',
            url: 'https://www.facebook.com/bens.sampaio',
        },
    ],
    interests: [
        'Traveling',
        'Cooking',
        'Cinema',
        'Literature',
        'Bouldering',
        'Lindyhop',
        'Yoga',
        'Board Games',
        'Video Games',
    ],
};
